builds:
- id: docker-machine-driver-cloudstack 
  main: ./bin/main.go
  binary: docker-machine-driver-cloudstack
  ldflags:
  - -s -w
  env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - linux
  goarch:
  - amd64
  ignore:
  - goos: darwin
    goarch: 386

archives:
- id: docker-machine-driver-cloudstack
  builds:
  - docker-machine-driver-cloudstack
  name_template: "docker-machine-driver-cloudstack_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  format: binary
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64

checksum:
  name_template: "checksums.txt"
