language: go

env:
  global:
    - GO111MODULE=on
    - GO_FOR_RELEASE=1.12
    - GOPROXY=https://proxy.golang.org

go:
  - 1.12
  - tip

install:
  - go get github.com/mitchellh/gox

after_success:
  - test -n "$TRAVIS_TAG" && test $TRAVIS_GO_VERSION = $GO_FOR_RELEASE && make release
