name: Go
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - uses: actions/checkout@v1

    - run: go get github.com/mitchellh/gox
    
  deploy:
    if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/')
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - uses: actions/checkout@v1
      
    - run: make release
      
    - name: release
      uses: goreleaser/goreleaser-action@v1
      with:
        args: --config goreleaser.yml
      env:
        GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
